created_at: '2025-11-26T16:54:48.823054'
engine:
  name: tophub
locked: true
name: ceo-news
scene: 上市公司董事长,关心国家政策,经济,科技,国内外大事
schedule:
  cron: 35 14 * * *
  custom_range:
    end: null
    start: null
  date_range: today
sources:
- category: 科技
  hashid: 5PdMP7pvmg
  name: 凤凰科技
  url: null
- category: 博客专栏
  hashid: DOvnyGpoEB
  name: 产品经理的人工智能学习库
  url: null
- category: 开发者
  hashid: rYqoXz8dOD
  name: 掘金
  url: null
- category: 电子报
  hashid: 4Kvxj2wekx
  name: 中国市场监管报
  url: null
- category: 综合
  hashid: Ywv4jRxePa
  name: 新浪热榜
  url: null
- category: 财经
  hashid: aqeEaZVe9R
  name: 美股市值
  url: null
- category: 电子报
  hashid: 1Vd5aZ5d85
  name: 中国改革报
  url: null
- category: 综合
  hashid: YKd6GDjeaP
  name: 半月谈
  url: null
- category: 财经
  hashid: 1VdJYjnvLQ
  name: 中国经济网
  url: null
- category: 财经
  hashid: 1VdJkxkeLQ
  name: 财联社
  url: null
- category: 财经
  hashid: WmoOWKDo4E
  name: 國外股市熱門
  url: null
- category: 科技
  hashid: Q1Vd5Ko85R
  name: 36氪
  url: null
- category: 综合
  hashid: KMZd7VOvrO
  name: 知乎日报
  url: null
- category: 政务
  hashid: 47o8ELqvMm
  name: 中国政府网
  url: null
- category: 政务
  hashid: YKd6JOqdaP
  name: 国家统计局
  url: null
- category: 财经
  hashid: 3QeLGVPd7k
  name: 财新网
  url: null
- category: 财经
  hashid: rx9ozj7oXb
  name: 新浪财经新闻
  url: null
- category: 科技
  hashid: NRrvWYDe5z
  name: 极客公园
  url: null
- category: 电子报
  hashid: x9oz03bdXb
  name: 人民日报
  url: null
- category: 科技
  hashid: KGoRAz2el6
  name: cnBeta
  url: null
- category: 电子报
  hashid: YqoXVNzdOD
  name: 每日经济新闻
  url: null
- category: 电子报
  hashid: JndkwKpd3V
  name: 中国经济周刊
  url: null
status:
  current_status: success
  enabled: true
  last_error: null
  last_run: '2025-12-01T14:20:50.759263'
  last_success_count: 158
  next_run: null
  progress:
    collected_articles: 154
    current_source: 极客公园
    processed_sources: 17
    status: collecting
    total_sources: 22
  running: false
  total_runs: 1
weaviate:
  collection: Ceo_news_db
