created_at: '2025-11-29T00:25:28.682045'
engine:
  name: tophub
locked: true
name: debug_task
scene: debug scene
schedule:
  cron: 0 8 * * *
  custom_range:
    end: null
    start: null
  date_range: last_1_days
sources:
- category: tech
  hashid: test_id
  name: Test Source
  url: http://example.com
status:
  enabled: true
  last_error: null
  last_run: null
  next_run: null
  total_runs: 0
weaviate:
  collection: Debug_task_db
