created_at: '2025-11-26T21:36:40.615025'
engine:
  name: tophub
locked: true
name: news-task
scene: 一个董事长,关心国家大事, 经济信息, 科技信息
schedule:
  cron: 0 8 * * *
  custom_range:
    end: null
    start: null
  date_range: last_1_days
sources:
- category: 政务
  display: 最新政策
  hashid: 47o8ELqvMm
  name: 中国政府网
- category: 政务
  display: 最新数据发布
  hashid: YKd6JOqdaP
  name: 国家统计局
- category: 科技
  display: 24小时热榜
  hashid: Q1Vd5Ko85R
  name: 36氪
- category: 电子报
  display: 电子报
  hashid: x9oz03bdXb
  name: 人民日报
- category: 电子报
  display: 电子报
  hashid: YqoXVNzdOD
  name: 每日经济新闻
- category: 科技
  display: ''
  hashid: WmoOGBko4E
  name: 全天候科技
- category: 财经
  display: 新闻排行周榜
  hashid: 0MdKam4ow1
  name: 第一财经
- category: 电子报
  display: 电子报
  hashid: JndkwKpd3V
  name: 中国经济周刊
- category: 科技
  display: 热门文章榜单
  hashid: L4MdAA1dxD
  name: 钛媒体
- category: 政务
  display: 政策解读
  hashid: nBe0B3bv37
  name: 中国政府网
- category: 政务
  display: 数据解读
  hashid: Ywv4J0xePa
  name: 国家统计局
- category: 政务
  display: 最新文件
  hashid: KGoRJbZol6
  name: 国家税务总局
- category: 政务
  display: 政策发布
  hashid: 1Vd5Rm5e85
  name: 中华人民共和国商务部
- category: 科技
  display: 热文
  hashid: 5VaobgvAj1
  name: 虎嗅网
- category: 科技
  display: 每日最新
  hashid: NRrvWYDe5z
  name: 极客公园
- category: 科技
  display: 热门文章
  hashid: Y2KeDGQdNP
  name: 少数派
- category: 财经
  display: 点击量排行
  hashid: rx9ozj7oXb
  name: 新浪财经新闻
- category: 财经
  display: 点击排行榜
  hashid: x9ozBY7oXb
  name: 财新网
- category: 财经
  display: 评论排行榜
  hashid: 3QeLGVPd7k
  name: 财新网
- category: 财经
  display: 日排行
  hashid: G2me3ndwjq
  name: 华尔街见闻
- category: 科技
  display: 每日最新
  hashid: KGoRAz2el6
  name: cnBeta
- category: 电子报
  display: 电子报
  hashid: 12owmgwdNV
  name: 光明日报
- category: 电子报
  display: 电子报
  hashid: qndggymdLl
  name: 第一财经日报
- category: 电子报
  display: 电子报
  hashid: 3QeLlrxe7k
  name: 经济参考报
- category: 电子报
  display: 电子报
  hashid: 0MdKwZ4dw1
  name: 经济观察报
- category: 电子报
  display: 电子报
  hashid: x9oz027dXb
  name: 证券日报
- category: 电子报
  display: 电子报
  hashid: WmoOlyBv4E
  name: 科技日报
- category: 综合
  display: 实时热点
  hashid: Jb0vmloB1G
  name: 百度
- category: 综合
  display: 热榜
  hashid: wWmoO5Rd4E
  name: 澎湃
status:
  enabled: true
  last_error: null
  last_run: '2025-11-26T21:45:35.056851'
  next_run: null
  total_runs: 1
weaviate:
  collection: News_task_db
