created_at: '2025-11-26T21:12:01.046381'
engine:
  name: tophub
locked: true
name: news33
scene: 董事长 关心国家大事 金融,科技
schedule:
  cron: 0 8 * * *
  custom_range:
    end: null
    start: null
  date_range: last_1_days
sources:
- category: 政务
  display: 调查研究 ‧ 政策解读
  hashid: BwdG5WLoPx
  name: 国务院发展研究中心
- category: 科技
  display: 每日新鲜事
  hashid: Jb0vmkWeB1
  name: 互联网的一些事
- category: 财经
  display: TOP100
  hashid: aqeEaZVe9R
  name: 美股市值
- category: 博客专栏
  display: ''
  hashid: DOvnyGpoEB
  name: 产品经理的人工智能学习库
- category: 大学
  display: 招考政策
  hashid: YqoXbjzdOD
  name: 北京教育考试院
- category: 开发者
  display: 人工智能本周最热
  hashid: rYqoXz8dOD
  name: 掘金
- category: 电子报
  display: 电子报
  hashid: 5PdMlB0vmg
  name: 金融投资报
- category: 社区
  display: 互联网
  hashid: 8Rv2k11dLw
  name: V2EX
- category: 综合
  display: 今日辟谣
  hashid: 12owJ2keNV
  name: 中国互联网联合辟谣平台
- category: 政务
  display: 政务公开 > 政策 > 发展改革委令
  hashid: 3QeLwpAd7k
  name: 中华人民共和国国家发展和改革委员会
- category: 科技
  display: ''
  hashid: n3moBJEoN5
  name: 9to5Google
- category: 财经
  display: 股市滚动新闻
  hashid: 1VdJYjnvLQ
  name: 中国经济网
- category: 博客专栏
  display: ''
  hashid: Vaobay3eAj
  name: 互联网分析在中国
- category: 大学
  display: 最新通知
  hashid: 47o8O60eMm
  name: 华中科技大学人工智能和自动化学院
- category: 开发者
  display: 人工智能热榜
  hashid: 47o8bRLdMm
  name: CSDN博客
- category: 电子报
  display: 电子报
  hashid: 1Vd5aZ5d85
  name: 中国改革报
- category: 社区
  display: 用利息生活｜投资理财
  hashid: 2me3AR0vwj
  name: 豆瓣小组
- category: 综合
  display: 改革创新
  hashid: YKd6GDjeaP
  name: 半月谈
- category: 政务
  display: 政务公开 > 解读 > 政策图解
  hashid: ARe13x2v7n
  name: 中华人民共和国国家发展和改革委员会
- category: 科技
  display: 滚动资讯
  hashid: proPkqneq6
  name: 投资界
- category: 财经
  display: 股市
  hashid: 1VdJkxkeLQ
  name: 财联社
- category: 博客专栏
  display: ''
  hashid: wkvlMkrdz1
  name: 水星投资理财
- category: 大学
  display: 新闻
  hashid: 5PdMV7Eemg
  name: 华中科技大学人工智能和自动化学院
- category: 开发者
  display: 精选
  hashid: YqoXwLneOD
  name: PMCAFF互联网产品社区
- category: 社区
  display: 终端与移动互联网
  hashid: anoppp9olZ
  name: 通信人家园
- category: 综合
  display: 政策
  hashid: ARe1mZ4e7n
  name: 中国服装产业网
- category: 政务
  display: 政务公开 > 解读 > 政策解读
  hashid: 12owDBmvNV
  name: 中华人民共和国国家发展和改革委员会
- category: 科技
  display: 互联网
  hashid: yjvQlDnobg
  name: ZAKER
- category: 财经
  display: 每周精选
  hashid: WmoOWKDo4E
  name: 國外股市熱門
- category: 博客专栏
  display: 人工智能学习笔记
  hashid: proPVK4dq6
  name: 知乎专栏
status:
  enabled: true
  last_error: null
  last_run: null
  next_run: null
  total_runs: 0
weaviate:
  collection: News33_db
