created_at: '2025-11-26T19:26:56.490340'
engine:
  name: tophub
locked: true
name: news-基金经理
scene: 基金经理
schedule:
  cron: 0 8 * * *
  custom_range:
    end: null
    start: null
  date_range: last_1_days
sources:
- category: 博客专栏
  display: ''
  hashid: ARe1AW2e7n
  name: 勃勃的美股投资日记
- category: 娱乐
  display: ''
  hashid: x9ozOzJvXb
  name: The Independent - Film
- category: 开发者
  display: Trending TypeScript Today
  hashid: YqoXWQ0eOD
  name: GitHub
- category: 政务
  display: 证监会要闻
  hashid: yjvQxM4obg
  name: 中国证券监督管理委员会
- category: 电子报
  display: 电子报
  hashid: 5PdMlB0vmg
  name: 金融投资报
- category: 社区
  display: 股票区24小时榜
  hashid: pQvNy5yoNE
  name: 虎扑社区
- category: 科技
  display: 滚动资讯
  hashid: proPkqneq6
  name: 投资界
- category: 综合
  display: Special report
  hashid: nBe0xabe37
  name: The Economist
- category: 财经
  display: TOP100
  hashid: aqeEaZVe9R
  name: 美股市值
- category: 博客专栏
  display: ''
  hashid: 3QeLXOze7k
  name: News - Apple Developer
- category: 开发者
  display: Trending Vim Snippet Today
  hashid: proPWBpeq6
  name: GitHub
- category: 政务
  display: 上市公告-可转换债券
  hashid: m4ej6y4exE
  name: 深圳证券交易所
- category: 社区
  display: 最新发布
  hashid: aEdZM7VvrO
  name: 理想股票技术论坛
- category: 科技
  display: ''
  hashid: wkvllJ4vz1
  name: 'ScienceDirect Publication: European Journal of Cancer'
- category: 综合
  display: Special report
  hashid: m4ejJ3qexE
  name: The Economist
- category: 财经
  display: 公募
  hashid: m4ejw3qoxE
  name: 中国基金报
- category: 博客专栏
  display: ''
  hashid: x9ozBMJoXb
  name: Paper 安全技术精粹
- category: 开发者
  display: HackerNews日报
  hashid: KGoRE81el6
  name: SuperTechFans
- category: 政务
  display: 基金要闻
  hashid: 3QeLJ3wv7k
  name: 国家自然科学基金委员会
- category: 社区
  display: 股票区最新回复
  hashid: ENeYWykvY4
  name: 虎扑社区
- category: 科技
  display: ''
  hashid: RrvWVy3o5z
  name: Biogeomorphic landscape
- category: 综合
  display: Europe
  hashid: nBe0AwBo37
  name: The Economist
- category: 财经
  display: IPO研报
  hashid: 0MdKzZ5vw1
  name: 乌拉邦研报
- category: 博客专栏
  display: ''
  hashid: wkvlMkrdz1
  name: 水星投资理财
- category: 开发者
  display: Daily Papers
  hashid: KGoRE42el6
  name: Hugging Face
- category: 政务
  display: 科普快讯
  hashid: 2me3K7xewj
  name: 国家自然科学基金委员会
- category: 社区
  display: 最新热门
  hashid: Ywv4PKBvPa
  name: 理想股票技术论坛
- category: 综合
  display: Prospero
  hashid: pQvN7PJdNE
  name: The Economist
- category: 财经
  display: 最新文章
  hashid: 0MdKzp6vw1
  name: 美股之家
- category: 博客专栏
  display: ''
  hashid: 1Vd5a8Md85
  name: 深度投资笔记
status:
  enabled: true
  last_error: null
  last_run: null
  next_run: null
  total_runs: 0
weaviate:
  collection: News_基金经理_db
