created_at: '2025-11-27T09:58:38.139168'
engine:
  name: tophub
locked: true
name: news-jj2
scene: 基金经理,研报,最新国际大事,政策新闻
schedule:
  cron: 0 8 * * *
  custom_range:
    end: null
    start: null
  date_range: last_1_days
sources:
- category: 政务
  display: 最新政策
  hashid: 47o8ELqvMm
  name: 中国政府网
- category: 政务
  display: 最新数据发布
  hashid: YKd6JOqdaP
  name: 国家统计局
- category: 政务
  display: 发言人表态
  hashid: 3adqZlMeng
  name: 中华人民共和国外交部
- category: 科技
  display: 24小时热榜
  hashid: Q1Vd5Ko85R
  name: 36氪
- category: 财经
  display: 今日热门研报
  hashid: 5PdM1Qbdmg
  name: 慧博投研资讯
- category: 财经
  display: 热门研报
  hashid: 5PdM1rGdmg
  name: 投研星球
- category: 财经
  display: 新闻排行周榜
  hashid: 0MdKam4ow1
  name: 第一财经
- category: 财经
  display: 点击排行榜
  hashid: x9ozBY7oXb
  name: 财新网
- category: 开发者
  display: 最新
  hashid: qYwv4MNdPa
  name: 安全客
- category: 综合
  display: 最新
  hashid: K7GdaKLoQy
  name: 抽屉新热榜
- category: 综合
  display: 要闻
  hashid: RrvWOl3v5z
  name: 观察者网
- category: 综合
  display: 热门文章
  hashid: pQvNXgmeNE
  name: 南方周末
- category: 综合
  display: 今日焦点
  hashid: WYKd6LmoaP
  name: FT中文网
- category: 财经
  display: 评论排行榜
  hashid: 3QeLGVPd7k
  name: 财新网
- category: 财经
  display: 财经频道
  hashid: KGoRk0xvl6
  name: 新华网
- category: 综合
  display: 国际新闻
  hashid: qndg1WxoLl
  name: CCTV央视新闻
- category: 政务
  display: 调查研究 ‧ 政策解读
  hashid: BwdG5WLoPx
  name: 国务院发展研究中心
- category: 科技
  display: 72小时热文榜
  hashid: 3QeLX0Ge7k
  name: 创业邦
- category: 财经
  display: 今日要闻
  hashid: 4KvxE1ldkx
  name: 中新经纬
- category: 综合
  display: 热榜
  hashid: mproPpoq6O
  name: 知乎
status:
  current_status: error
  enabled: true
  last_error: TaskManager.update_task_status() got an unexpected keyword argument
    'last_run'
  last_run: '2025-11-27T18:06:18.259487'
  next_run: null
  progress: null
  running: false
  total_runs: 3
weaviate:
  collection: News_jj2_db
