created_at: '2025-11-26T21:02:46.363543'
engine:
  name: tophub
locked: true
name: news-jj
scene: 基金经理,国际大事,政治新闻,经济新闻
schedule:
  cron: 0 8 * * *
  custom_range:
    end: null
    start: null
  date_range: last_1_days
sources:
- category: 博客专栏
  display: ''
  hashid: 3moBJ1MoN5
  name: iPotato
- category: 大学
  display: 学术动态
  hashid: Q0or6pYo8B
  name: 山东大学能源与动力工程学院
- category: 政务
  display: 通知
  hashid: 0MdKENJow1
  name: 国家能源局
- category: 电子报
  display: 电子报
  hashid: proP8kkoq6
  name: 中国消费者报
- category: 社区
  display: 消费电子 IT新闻
  hashid: b0vmOK6eB1
  name: NGA玩家社区
- category: 综合
  display: 能源频道
  hashid: 47o8Q4LvMm
  name: 人民网
- category: 财经
  display: TOP100
  hashid: aqeEaZVe9R
  name: 美股市值
- category: 购物
  display: 消费众测榜
  hashid: WYKd6RqdaP
  name: 什么值得买
- category: 大学
  display: 学院新闻
  hashid: b0vm8l2oB1
  name: 山东大学能源与动力工程学院
- category: 政务
  display: 监管动态
  hashid: 3adqKV3ong
  name: 国家金融监督管理总局
- category: 电子报
  display: 电子报
  hashid: m4ejrgmexE
  name: 中国能源报
- category: 社区
  display: 不要买 | 消费主义逆行者
  hashid: yjvQ7WVebg
  name: 豆瓣小组
- category: 综合
  display: 改革创新
  hashid: YKd6GDjeaP
  name: 半月谈
- category: 财经
  display: 股市滚动新闻
  hashid: 1VdJYjnvLQ
  name: 中国经济网
- category: 购物
  display: 实时消费热点
  hashid: Ywv4PWzvPa
  name: 什么值得买
- category: 大学
  display: 建设与改革
  hashid: RrvWBjxo5z
  name: 西南科技大学教务处
- category: 政务
  display: 新闻动态 > 新闻发布
  hashid: x9oz3m6vXb
  name: 中华人民共和国国家发展和改革委员会
- category: 电子报
  display: 电子报
  hashid: ENeYkDjvY4
  name: 消费质量报
- category: 财经
  display: 股市
  hashid: 1VdJkxkeLQ
  name: 财联社
- category: 大学
  display: 通知公告
  hashid: m4ej6XqexE
  name: 山东大学能源与动力工程学院
- category: 政务
  display: 政务公开 > 政策 > 发展改革委令
  hashid: 3QeLwpAd7k
  name: 中华人民共和国国家发展和改革委员会
- category: 电子报
  display: 电子报
  hashid: 4Kvxj2wekx
  name: 中国市场监管报
- category: 财经
  display: 每周精选
  hashid: WmoOWKDo4E
  name: 國外股市熱門
- category: 政务
  display: 监管问询
  hashid: 3moBKwEvN5
  name: 上海证券交易所
- category: 电子报
  display: 电子报
  hashid: Vaob5yGeAj
  name: 消费日报
- category: 财经
  display: 地产财经频道
  hashid: Q0orL7Zd8B
  name: 中华网
- category: 政务
  display: 通知公告
  hashid: YKd6G6weaP
  name: 中华人民共和国国家发展和改革委员会
- category: 电子报
  display: 电子报
  hashid: 1Vd5aZ5d85
  name: 中国改革报
- category: 财经
  display: 股市榜
  hashid: 1Vd5NkWe85
  name: 头条热榜
- category: 政务
  display: 政务公开 > 解读 > 政策图解
  hashid: ARe13x2v7n
  name: 中华人民共和国国家发展和改革委员会
status:
  enabled: true
  last_error: null
  last_run: null
  next_run: null
  total_runs: 0
weaviate:
  collection: News_jj_db
