created_at: '2025-11-29T23:46:19.387141'
engine:
  name: tophub
locked: true
name: stock-news
scene: 一个2级市场的基金经理的参考新闻，需要涵盖国内外的新闻大事，政治，经济，科技，最好还有研报，还有美股的新闻
schedule:
  cron: 0 9 * * *
  custom_range:
    end: null
    start: null
  date_range: last_1_days
sources:
- category: 科技
  hashid: Q1Vd5Ko85R
  name: 36氪
  url: null
- category: 科技
  hashid: 5VaobgvAj1
  name: 虎嗅网
  url: null
- category: 综合
  hashid: x9ozB4KoXb
  name: 今日头条
  url: null
- category: 财经
  hashid: G2me3ndwjq
  name: 华尔街见闻
  url: null
- category: 财经
  hashid: rx9ozj7oXb
  name: 新浪财经新闻
  url: null
- category: 科技
  hashid: Y3QeLMPo7k
  name: Readhub
  url: null
- category: 科技
  hashid: L4MdAA1dxD
  name: 钛媒体
  url: null
- category: 科技
  hashid: 74Kvx59dkx
  name: IT之家
  url: null
- category: 科技
  hashid: NRrvWYDe5z
  name: 极客公园
  url: null
- category: 财经
  hashid: 3QeLGVPd7k
  name: 财新网
  url: null
- category: 综合
  hashid: RrvWVlgo5z
  name: 果壳
  url: null
- category: 综合
  hashid: pQvNXgmeNE
  name: 南方周末
  url: null
- category: 科技
  hashid: KGoRAz2el6
  name: cnBeta
  url: null
- category: 科技
  hashid: 3QeLX0Ge7k
  name: 创业邦
  url: null
- category: 财经
  hashid: 5PdM1Qbdmg
  name: 慧博投研资讯
  url: null
- category: 财经
  hashid: 5PdM1rGdmg
  name: 投研星球
  url: null
- category: 政务
  hashid: 47o8ELqvMm
  name: 中国政府网
  url: null
- category: 政务
  hashid: YKd6JOqdaP
  name: 国家统计局
  url: null
- category: 综合
  hashid: qYwv48MvPa
  name: FT中文网
  url: null
- category: 综合
  hashid: KMZd7GGdrO
  name: FT中文网
  url: null
- category: 财经
  hashid: 3QeLwYGd7k
  name: 雪球
  url: null
- category: 财经
  hashid: X12owXzvNV
  name: 雪球
  url: null
- category: 财经
  hashid: DOvn8x1eEB
  name: 经济观察网
  url: null
- category: 科技
  hashid: rYqoXMXvOD
  name: 新浪科技新闻
  url: null
- category: 科技
  hashid: ARe1QpLe7n
  name: 凤凰科技
  url: null
status:
  current_status: success
  enabled: false
  last_error: null
  last_run: '2025-11-30T11:01:04.087758'
  last_success_count: 6
  next_run: null
  progress: null
  running: false
  total_runs: 3
weaviate:
  collection: Task_4678f41b9b07465083cca3f169452dab
