created_at: '2025-11-29T00:42:52.798800'
engine:
  name: tophub
locked: true
name: te
scene: 金融新闻
schedule:
  cron: 0 8 * * *
  custom_range:
    end: null
    start: null
  date_range: last_1_days
sources:
- category: 财经
  hashid: 5PdM1Qbdmg
  name: 慧博投研资讯
  url: null
- category: 财经
  hashid: 5PdM1Qbdmg
  name: 慧博投研资讯
  url: null
- category: 财经
  hashid: 5PdM1Qbdmg
  name: 慧博投研资讯
  url: null
- category: 财经
  hashid: 5PdM1Qbdmg
  name: 慧博投研资讯
  url: null
- category: 财经
  hashid: 5PdM1Qbdmg
  name: 慧博投研资讯
  url: null
- category: 财经
  hashid: 5PdM1Qbdmg
  name: 慧博投研资讯
  url: null
- category: 财经
  hashid: 5PdM1Qbdmg
  name: 慧博投研资讯
  url: null
- category: 财经
  hashid: 5PdM1Qbdmg
  name: 慧博投研资讯
  url: null
- category: 财经
  hashid: 5PdM1Qbdmg
  name: 慧博投研资讯
  url: null
- category: 财经
  hashid: 5PdM1Qbdmg
  name: 慧博投研资讯
  url: null
status:
  current_status: success
  enabled: true
  last_error: null
  last_run: '2025-11-29T08:13:33.142540'
  last_success_count: 0
  next_run: null
  progress: null
  running: false
  total_runs: 3
weaviate:
  collection: Te_db
