created_at: '2025-11-29T14:19:55.291055'
engine:
  name: tophub
locked: true
name: test-8
scene: 基金经理，需要新闻来判断未来行情
schedule:
  cron: 0 8 * * *
  custom_range:
    end: null
    start: null
  date_range: last_1_days
sources:
- category: 财经
  hashid: 0MdKam4ow1
  name: 第一财经
  url: null
- category: 财经
  hashid: rx9ozj7oXb
  name: 新浪财经新闻
  url: null
- category: 财经
  hashid: X12owXzvNV
  name: 雪球
  url: null
- category: 财经
  hashid: G2me3ndwjq
  name: 华尔街见闻
  url: null
- category: 财经
  hashid: 3QeLGVPd7k
  name: 财新网
  url: null
- category: 财经
  hashid: YKd6RDqdaP
  name: 镝数
  url: null
- category: 政务
  hashid: 47o8ELqvMm
  name: 中国政府网
  url: null
- category: 政务
  hashid: YKd6JOqdaP
  name: 国家统计局
  url: null
- category: 科技
  hashid: Q1Vd5Ko85R
  name: 36氪
  url: null
- category: 综合
  hashid: mproPpoq6O
  name: 知乎
  url: null
status:
  current_status: success
  enabled: true
  last_error: null
  last_run: '2025-11-29T14:22:28.226400'
  last_success_count: 54
  next_run: null
  progress: null
  running: false
  total_runs: 1
weaviate:
  collection: Task_3b61dc0e1b7748138bb2ae60ed24eacc
