created_at: '2025-11-29T11:40:38.131634'
engine:
  name: tophub
locked: true
name: 医疗
scene: 医疗新闻
schedule:
  cron: 0 8 * * *
  custom_range:
    end: null
    start: null
  date_range: last_1_days
sources:
- category: 电子报
  hashid: DgeyK5wvZq
  name: 健康时报
  url: null
- category: 电子报
  hashid: 5PdMlDZvmg
  name: 中国医药报
  url: null
- category: 电子报
  hashid: KGoRZVxol6
  name: 中国•企业家日报
  url: null
- category: 电子报
  hashid: 47o89EgvMm
  name: 医药经济报
  url: null
- category: 博客专栏
  hashid: 12owWqmoNV
  name: UX Coffee 设计咖
  url: null
- category: 大学
  hashid: 0MdK2j5vw1
  name: 安徽医科大学研究生学院
  url: null
- category: 博客专栏
  hashid: G47o8nqdMm
  name: PanSci 泛科學
  url: null
- category: 政务
  hashid: x9ozwADvXb
  name: 中国互联网联合辟谣平台
  url: null
- category: 科技
  hashid: 20MdK2vw1q
  name: 果壳
  url: null
- category: 科技
  hashid: WmoOGBko4E
  name: 全天候科技
  url: null
- category: 综合
  hashid: wWmoO5Rd4E
  name: 澎湃
  url: null
status:
  current_status: success
  enabled: true
  last_error: null
  last_run: '2025-11-29T13:16:00.082591'
  last_success_count: 2
  next_run: null
  progress: null
  running: false
  total_runs: 2
weaviate:
  collection: Task_877f4a2530fc45ebbe860438e8692888
