created_at: '2025-11-29T00:01:06.416102'
engine:
  name: tophub
locked: true
name: 工程师
scene: 工程师工程新闻
schedule:
  cron: 0 8 * * *
  custom_range:
    end: null
    start: null
  date_range: last_1_days
sources: []
status:
  current_status: success
  enabled: true
  last_error: null
  last_run: '2025-11-29T00:01:30.740555'
  last_success_count: 0
  next_run: null
  progress: null
  running: false
  total_runs: 2
weaviate:
  collection: 工程师_db
