created_at: '2025-11-29T15:12:53.697549'
engine:
  name: tophub
locked: true
name: 金融6
scene: 金融新闻
schedule:
  cron: 0 8 * * *
  custom_range:
    end: null
    start: null
  date_range: last_1_days
sources:
- category: 测试
  hashid: test123
  name: 测试源1
  url: null
- category: 测试
  hashid: test456
  name: 测试源2
  url: null
status:
  current_status: success
  enabled: true
  last_error: null
  last_run: '2025-11-29T15:17:25.351578'
  last_success_count: 89
  next_run: null
  progress: null
  running: false
  total_runs: 1
weaviate:
  collection: Task_7869214ccc6a474d9d4cd1eebdab6d0d
